gretty-gradle-plugin/gretty

- libs/gretty/src/main/groovy/org/akhikhl/gretty/StartBaseTask.groovy
Gradle 4.6 introduced a `getJvmArgumentProviders` which it expects to
never return `null`. If `null` is returned, then applying the
`JacocoPluginExtension` fails.
> Fix compatibility with Gradle 4.6

- libs/gretty-runner/src/main/groovy/org/akhikhl/gretty/Runner.groovy
Fixed #13.  See notes in issue about how Groovy can see odd results for `this.getClass()`.
> Fixed resource-loading of default logback config file

- libs/gretty-runner-tomcat8/build.gradle
- libs/gretty/src/main/groovy/org/akhikhl/gretty/ServletContainerConfig.groovy
Due to the following thread:
http://tomcat.10.x6.nabble.com/ANN-Apache-Tomcat-8-5-3-available-td5051828.html
Fixes https://github.com/akhikhl/gretty/pull/369
PR copied from https://github.com/akhikhl/gretty/pull/373
> Remove tomcat-embed-logging-log4j from Tomcat 8.5.3 on

- integrationTests/buildSrc/gretty-integrationTest/src/main/groovy/org/akhikhl/gretty/internal/integrationTests/IntegrationTestPlugin.groovy
Another change towards a JDK9 `testAll` clean run, although that still seems a way off.
In theory I think here we could add some Jetty directives to up the requested class compat to 6, but it also seems reasonable to exclude Jetty 7&8 now when compiling/testing with JDK9.
> Exclude Jetty7/8 in testAll when running JDK9. Fixed #15.

- .travis.yml
Starting to unpack the release-procedure.  I see this tag-triggered build in Travis, but it fails or would fail for two reasons:
1. The tag will be for a release build and it looks like these are run locally, so the Travis build fails because the artifact of that version is already deployed.
1. Travis doesn't have all of the secrets it needs to GPG sign the build.  Probably fair enough - Bintray can hold both the secret key and passphase, but who really wants to do that.  The current build script can look for a passed `project.bintrayKeyPhrase`, but I don't think Travis is currently set-up to pass that as environment like some of the other keys.
Last couple of tag builds fail on Travis due to duplicates, so the tag is already released:
- …
> Removed tag-triggered build from Travis

- .travis.yml
- build.gradle
- integrationTests/buildSrc/gradle.properties
- integrationTests/buildSrc/gretty-integrationTest/build.gradle
- integrationTests/buildSrc/gretty-integrationTest/src/main/groovy/org/akhikhl/gretty/internal/integrationTests/BasePlugin.groovy
- integrationTests/buildSrc/gretty-integrationTest/src/main/groovy/org/akhikhl/gretty/internal/integrationTests/IntegrationTestPlugin.groovy
- integrationTests/buildSrc/gretty-integrationTest/src/main/resources/org/akhikhl/gretty/internal/integrationTests/project.properties
- integrationTests/config/gebConfig/GebConfig.groovy
- integrationTests/websocket/build.gradle
- integrationTests/websocket/src/main/webapp/index.html
This changeset allows the full `testAll` `integrationTests` suite to be run on Linux/Travis.  This should improve pre-release testing since we no longer need to rely on running the integration tests solely on a developer's MacOS environment.
Started by noticing that the Gecko driver was hard-coded to the `macos` dist, so externalized this, retaining the current default.  Due to the way `integrationTests` is called as a separate Gradle project, I needed to provide a mechanism to allow dist/version overrides to be plumbed-through, as these properties are in `integrationTests`.
The remainder is mostly solving issues found with running (headless?) on Linux/Travis.  I needed to update Selenium and Geb.  Also needed to update the Gecko driver, but the equivalent version caused problems for me …
> Run integrationTests/testAll on Travis

- .travis.yml
- build.gradle
- integrationTests/buildSrc/gradle.properties
- integrationTests/buildSrc/gretty-integrationTest/build.gradle
- integrationTests/buildSrc/gretty-integrationTest/src/main/groovy/org/akhikhl/gretty/internal/integrationTests/BasePlugin.groovy
- integrationTests/buildSrc/gretty-integrationTest/src/main/groovy/org/akhikhl/gretty/internal/integrationTests/FarmIntegrationTestPlugin.groovy
- integrationTests/buildSrc/gretty-integrationTest/src/main/groovy/org/akhikhl/gretty/internal/integrationTests/IntegrationTestPlugin.groovy
- integrationTests/buildSrc/gretty-integrationTest/src/main/resources/org/akhikhl/gretty/internal/integrationTests/project.properties
First-pass at changing the Travis build for integration-tests `testAll` to be a matrix of JDK x ServletContainer (for JDK8, other JDKs currently skip `testAll`).  This parallelises the build and avoids long builds and Travis timeouts whilst retaining best coverage.
Note the approach here for new build prop `testAllContainers` is that it is applied as `retainAll` on the existing collection of containers to run for a test.  This rather than replacing, as some tests are already self-limiting e.g. might exclude `jetty7`, so when you want to test only `jetty7` by applying set intersection you won't run additional, unwanted tests.
Main feedback requested - the variable name isn't great ... any suggestions for improvements, or is it OK ... I thought maybe `testOnlyContainers` might be better? …
> testAll split/parallelisation by-container with testAllContainers/TEST_ALL_CONTAINERS

- .travis.yml
- README.md
- changes.md
- common.gradle
- libs/gretty/build.gradle
Now that `master` is `3.x`, kicking-off the platform-support deprecations/removals with JDK7, which is a fairly small change.
> Remove JDK7 support and references

- libs/gretty-core/src/main/groovy/org/akhikhl/gretty/ServerConfig.groovy
- libs/gretty/src/main/groovy/org/akhikhl/gretty/ServletContainerConfig.groovy
Another small compatibility change for 3.x - currently the default `servletContainer` (when none or bad supplied) is `jetty9`, which means Jetty 9.2.  This change makes it Jetty 9.4, with the exact runtime version taken from `jetty94_version` which currently defaults to `9.4.10.v20180503`.
There's actually a couple of rough edges with Jetty 9.4 support, but I think we just need to accept that and work through them for 3.x - need to be on the latest Jetty branch by-default.
Testing - `./gradlew build` then cd to `integrationTests/helloGretty` and run `../gradlew appRunWar`.  That project has no `servletContainer` in `build.gradle` and so will move from Jetty 9.2 to 9.4 with this change.
> Make the default servlet container jetty9.4 (Jetty 9.4)

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- integrationTests/build.gradle
- integrationTests/buildSrc/settings.gradle
- integrationTests/gradle/wrapper/gradle-wrapper.properties
- integrationTests/settings.gradle
- settings.gradle
* Upgrades to Gradle 4.8 ([release notes](https://docs.gradle.org/4.8/release-notes.html))
* Enable stable publishing feature ahead of Gradle 5.0 release
> Gradle 4.8

- .travis.yml
- integrationTests/buildSrc/gretty-integrationTest/src/main/groovy/org/akhikhl/gretty/internal/integrationTests/FarmIntegrationTestPlugin.groovy
- integrationTests/buildSrc/gretty-integrationTest/src/main/groovy/org/akhikhl/gretty/internal/integrationTests/IntegrationTestPlugin.groovy
- libs/gretty-runner-jetty/src/main/groovy/org/akhikhl/gretty/JettyServerConfigurer.groovy
- libs/gretty-runner-jetty94/src/main/groovy/org/akhikhl/gretty/JettyConfigurerImpl.groovy
- libs/gretty-runner/src/main/resources/grettyRunnerLogback.groovy
This puts Jetty 9.3 and 9.4 `integrationTests` execution into the Travis matrix, with the required fixes and exclusions in-place.
Fixes #61.
> Run integrationTests for Jetty 9.3 and 9.4

- libs/gretty-core/build.gradle
- libs/gretty/src/main/groovy/org/akhikhl/gretty/CertificateGenerator.groovy
Bouncy Castle 1.47 introduces a bunch of API changes that break compatibility ([see here](http://www.bouncycastle.org/wiki/display/JA1/Porting+from+earlier+BC+releases+to+1.47+and+later)).
This can create classpath problems between Gretty and other Gradle plugins. Keeping Bouncy Castle up to date can hopefully make Gretty play nice with the latest versions of other plugins.
> Update Bouncy Castle to 1.60

- libs/gretty-core/src/main/groovy/org/akhikhl/gretty/LauncherBase.groovy
- libs/gretty-runner-jetty/src/main/groovy/org/akhikhl/gretty/JettyServerConfigurer.groovy
- libs/gretty-runner-tomcat/src/main/groovy/org/akhikhl/gretty/TomcatServerConfigurer.groovy
- libs/gretty/src/main/groovy/org/akhikhl/gretty/ProductConfigurer.groovy
initParameters were wrongly serialized as initParams into server.json config file on producBuild task.
`integrationTests/testInitParameter` test can be used for verification, without the fix result of the `productBuild` task is not runnable.
> Fix wrong serization of the initParameters in productBuild

- libs/gretty-core/src/main/groovy/org/akhikhl/gretty/LauncherBase.groovy
- libs/gretty-runner/src/main/groovy/org/akhikhl/gretty/LogUtil.groovy
- libs/gretty-runner/src/main/groovy/org/akhikhl/gretty/Runner.groovy
- libs/gretty-runner/src/main/resources/grettyRunnerLogback.groovy
Prior to this patch, Gretty uses Logbacks default log level
of DEBUG until the server start command had been received,
and Gretty reconfigures Logback according to the server
parameters.
This has caused a situation in which log messages prior to
server start are useful (command line arguments, network
setup, commands received other than 'server start'), but
were not properly thresholded.
This patch establishes a log level for all log messages
prior to receiving the server start command. To this end,
the runner accepts a "--debug" command line flag to turn
on debug logging, and sets INFO otherwise.
The Gretty Gradle process invoking the runner turns on the
debug flag only if its process itself was invoked with
"--debug", as in `./gradlew --debug :helloGretty:appRun`.
This type of setup is …
> Set initial log level (fixes #150)

- libs/gretty-core/src/main/groovy/org/akhikhl/gretty/LauncherBase.groovy
Because #138 removed adequate error handling, the check for
already used ports was broken and caused Gretty to fail in
case the 'gretty_ports.properties' file was present.
I think the check is now obsolete because #138 removed the
ability to manually specify fixed service and status ports
for Gretty. As a result, Gretty's ports will never clash
from one Gretty invocation to the next.
If the check was restored, it would only check if the
previous Gretty invocation had already terminated.
If one of the *servlet container ports* clashed, I deem
the current behavior (BindException) sufficient.
---
tl;dr: I tried to wrap my head around the question why would anybody check the ports of the prior execution and could not find a good answer. Maybe the check made sense when we still could tell …
> Remove malformed check for already used ports (fixes #147)

- integrationTests/helloGretty/build.gradle
- integrationTests/helloGrettySecure/build.gradle
- libs/gretty-runner-tomcat/src/main/groovy/org/akhikhl/gretty/TomcatServerConfigurer.groovy
This PR contains a couple of general fixes / improvements, which I developed while integrating Tomcat 10 (#144 / #159), that are also useful to existing Tomcat servlet containers prior to version ten.
The changes common motive consists of limiting usage of the stringly-typed method `Connector#setProperty(String name, String value)`:
1. For the SSL commit, this means explicitly creating a `SSLHostConfig`. This gets rid of properties which are already deprecated in Tomcat 9, and cease to exist in Tomcat 10.
2. For `httpsIdleTimeout`, the caller failed to match the signature of `setProperty`, because the second argument was of type Integer, causing a runtime error that prevented using that feature.
3. For `maxPostSize`, that call of `setProperty` never worked, because the target object has …
> Limit usage of Tomcat's Connector#setProperty to a minimum

- libs/gretty-runner-jetty94/src/main/groovy/org/akhikhl/gretty/JettyConfigurerImpl.groovy
- Reference : [Issue #2468 - Remove SoLinger.](https://github.com/eclipse/jetty.project/pull/2644)
- Hello, I using jetty version 9.4 in gretty. when i started to server with command(`./gradlew jettyRunWar`), the message below being printed out.
- The message is because the `soLingerTime` has been deprecated in Jetty 9.4 version.
```
WARN Ignoring deprecated socket close linger time
```
- I'm not sure if this MR is correct way 😄 Thank you for providing a good plug-in.
> Delete deprecated method in jetty 9.4

- integrationTests/farm/MyWebApp/build.gradle
- integrationTests/farm/MyWebApp/src/main/java/org/akhikhl/examples/gretty/MyWebAppContextListener.java
- integrationTests/farm/MyWebApp/src/main/webapp/WEB-INF/web.xml
- libs/gretty-runner-jetty/src/main/groovy/org/akhikhl/gretty/JettyServerConfigurer.groovy
- libs/gretty-runner-jetty/src/main/groovy/org/akhikhl/gretty/JettyServerManager.groovy
- libs/gretty-runner-jetty7/src/main/groovy/org/akhikhl/gretty/JettyConfigurerImpl.groovy
- libs/gretty-runner-jetty8/src/main/groovy/org/akhikhl/gretty/JettyConfigurerImpl.groovy
- libs/gretty-runner-jetty9/src/main/groovy/org/akhikhl/gretty/JettyConfigurerImpl.groovy
- libs/gretty-runner-jetty93/src/main/groovy/org/akhikhl/gretty/JettyConfigurerImpl.groovy
- libs/gretty-runner-jetty94/src/main/groovy/org/akhikhl/gretty/JettyConfigurerImpl.groovy
- libs/gretty-runner-tomcat/src/main/groovy/org/akhikhl/gretty/TomcatServerConfigurer.groovy
- libs/gretty-runner-tomcat/src/main/groovy/org/akhikhl/gretty/TomcatServerManager.groovy
This change makes sure that apps are started and become available in the order in which they are defined in the farm config.
Order was kind of already guaranted because gretty is using `[:]` for webapps list (which is LinkedHashMap), but server was available only when all webapps were initialized. So it was not possible to have webapps to depend on the availability of other apps.
As a side-effect I've also discovered bug with `redeployMode = "redeploy"` for jetty container. This change fixes it. 
Previously old contexts were properly stopped only on the first redeploy, but all subsequent redeploys didn't actually stop old contexts. Only new contexts were reachable from the web server but old ones were still hanging in the memory.
This change is covered by integration test, see `farm` …
> Non-blocking farm initialization. Fix context cleanup on "redeploy".

- integrationTests/gradle.properties
- libs/gretty/src/main/groovy/org/akhikhl/gretty/AppAfterIntegrationTestTask.groovy
- libs/gretty/src/main/groovy/org/akhikhl/gretty/AppBeforeIntegrationTestTask.groovy
- libs/gretty/src/main/groovy/org/akhikhl/gretty/AppServiceTask.groovy
- libs/gretty/src/main/groovy/org/akhikhl/gretty/AppStartTask.groovy
- libs/gretty/src/main/groovy/org/akhikhl/gretty/FarmStartTask.groovy
- libs/gretty/src/main/groovy/org/akhikhl/gretty/StartBaseTask.groovy
- libs/gretty/src/main/groovy/org/akhikhl/gretty/TaskWithServerConfig.groovy
- libs/gretty/src/main/groovy/org/akhikhl/gretty/TaskWithWebAppConfig.groovy
- libs/gretty/src/main/groovy/org/akhikhl/gretty/WebAppConfigWithInputs.groovy
I did some reading & analysis and this fixes a couple of warnings from #133. I'm very unsure about this solution, please see for yourself and decide if we need to rethink. I dislike:
- the amount of boilerplate added: if it weren't for the `@Delegate`, we could just annotate the Groovy property as in:  
```groovy
class WebAppConfig {
@Input
@Optional
def contextPath
// ...
}
```
- making "gretty-core" dependent on Gradle's API, polluting those data transfer objects with Gradle-specific input and output logic.
@boris-petrov I made this a draft PR - please tell me what you think and then we figure out how to proceed.
> Annotate `WebAppConfig` to fix Gradle Deprecation Warnings

- integrationTests/farmJacoco/MyWebApp/build.gradle
instead of changing the collections in a `doFirst`. That removes a
deprecation warning from that sample.
> Lazily add source and classes dirs

- libs/gretty/build.gradle
- libs/gretty/src/main/resources/META-INF/gradle-plugins/org.gretty.properties
This adds validation for the task classes which is run on check.
It also currently adds a Maven publication called `PluginMavenPublication` to the `gretty` subproject. The `PluginMaven` publishes the same things as the `MavenJava` publication, so if you publish both things they will override each other. I checked the publication code, and it seem like only one publication is published when publishing, so I think we are good. Is there any way to try this out?
> Use java gradle plugin

- buildSrc/build.gradle
- buildSrc/src/main/groovy/grettybuild.common.gradle
This PR builds on top of https://github.com/gretty-gradle-plugin/gretty/pull/200 and removes the maven plugin from the build, so only the new publishing mechanism is in use.
> Remove maven plugin for publishing

- libs/gretty-runner-jetty/src/main/groovy/org/akhikhl/gretty/JettyServerConfigurer.groovy
- libs/gretty-runner-tomcat/src/main/groovy/org/akhikhl/gretty/TomcatServerConfigurer.groovy
- libs/gretty-springboot/src/main/groovy/org/akhikhl/gretty/AppServletInitializer.java
This one's a bit harder to explain. This is the only commit that is in my prototypical Jetty 10 branch, but not in master. It's a fix for crash resulting in the combination of classloader rework of Jetty 10 onwards, and the way how Spring integration has been done in Gretty.
- This means for master it's an existing solution for a problem yet-to-come, namely the day we can re-enable Spring integration. Classloading has been reworked in both Jetty 10 and 11, in a way that defers the creation of the classloader to the point where the webapp starts. Trying to load a class before the webapp starts will crash. This is a fix to a dormant fault already in Gretty, just not active because we do not have Spring integration ready as of today. You may notice that it still uses 'javax.'-APIs. This is …
> Spring support: avoid classloading of webapp classes before webapp start

- libs/gretty/build.gradle
> Fix Invalid plugin ID 'org.gretty' when running publishPlugins

- libs/gretty/src/main/groovy/org/akhikhl/gretty/ProjectUtils.groovy
I encountered some errors when using this plugin:
1. The transitive dependencies from the sub-module are not excluded even though I added `implementation.exclude module: 'xxx'` in the `configurations` block.
2. The final dependencies contain the duplicated modules with different versions if two modules depend on two different versions.
Then I did some investigation and found that the logic of resolving the project dependencies look problematic. That is, for a multi-module project, it will iterate all the modules and get the dependencies separately, then put them together to produce the final dependencies. But in fact, the final dependencies of a multi-module project are not equal to the sum of its sub-modules' dependencies in most cases. That could explain the problems I encountered.
I …
> Improve the dependency resolving logic

- libs/gretty/src/main/groovy/org/akhikhl/gretty/GrettyPlugin.groovy
> Avoid calling afterEvaluate on already evaluated project

- libs/gretty/src/main/groovy/org/akhikhl/gretty/ProjectUtils.groovy
- libs/gretty/src/main/groovy/org/akhikhl/gretty/StartBaseTask.groovy
I'm using the gretty plugin in a complex project, which has the `org.springframework.boot` group id in its `complieClasspath` and that could make gretty treat the project as a spring boot project, but actually it's not a standard spring boot application. So I want to tell gretty that it's not a spring boot project explicity.
I noticed that gretty has an undocumented option named `springBoot` that indicates whether the current project is a spring boot project or not. But we couldn't set it to `false` explicitly to indicates that a project is not a spring boot project. Because inside gretty, it will try to resolve the spring boot dependency when the `springBoot` option is a falsy value. I personally think it doesn't make sense when we the user set it to `false` explicitly. …
> Use the `springBoot` option when it is not null

- .github/workflows/ci.yml
- build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/groovy/grettybuild.common.gradle
- gradle.properties
- integrationTests/build.gradle
- integrationTests/buildSrc/build.gradle
- integrationTests/buildSrc/gretty-integrationTest/build.gradle
- integrationTests/buildSrc/gretty-integrationTest/src/main/groovy/org/akhikhl/gretty/internal/integrationTests/BasePlugin.groovy
- integrationTests/buildSrc/gretty-integrationTest/src/main/groovy/org/akhikhl/gretty/internal/integrationTests/IntegrationTestPlugin.groovy
- integrationTests/buildSrc/gretty-integrationTest/src/main/resources/org/akhikhl/gretty/internal/integrationTests/project.properties
- integrationTests/spring-boot-farm-secure/spring-boot-app/build.gradle
- integrationTests/spring-boot-farm-secure/spring-boot-webservice/build.gradle
- integrationTests/spring-boot-farm/spring-boot-app/build.gradle
- integrationTests/spring-boot-farm/spring-boot-webservice1/build.gradle
- integrationTests/spring-boot-farm/spring-boot-webservice2/build.gradle
- integrationTests/spring-boot-simple/build.gradle
- integrationTests/springBootWebSocket/build.gradle
- integrationTests/webfragment/build.gradle
- libs/gretty-common/build.gradle
- libs/gretty-core/build.gradle
- libs/gretty-filter/build.gradle
- libs/gretty-runner/build.gradle
- libs/gretty-spock/build.gradle
- libs/gretty-springboot/build.gradle
- libs/gretty-starter/build.gradle
- libs/gretty/src/main/groovy/org/akhikhl/gretty/GrettyPlugin.groovy
Due to the recent improvements with regards to Gradle 7, I thought I might add a build job, too. The Gradle upgrade also implies using Groovy 3, which takes me to a major point: I think it is pointless for Gretty to do any effort in actively managing a specific version of Groovy. Instead, Gretty should rely on the Groovy version shipped with Gradle. I mean, Groovy and Gradle versions always co-evolve: I don't think its meaningful to lag behind Gradle's Groovy version, or to anticipate future changes of Gradle to the Groovy version. The added build shows that we can target Groovy 2 and 3 (and therefore Gradle 6.x and 7.x) just fine. This results in the following course of action:
- Adding a Gradle 7.x build job
- Pruning all occurrences of `groovy_version`
- Opting in to the Groovy …
> Add Gradle 7 build job (and support Groovy 3)

- libs/gretty-runner-jetty11/src/main/groovy/org/akhikhl/gretty/JettyConfigurerImpl.groovy
When stripping the redundant FilteringClassLoader for Jetty 11
in ed5c9267058c95b526c88acefc3b6b012b53f863, I also stripped
the list of patterns which seemed unreasonable at the time.
I now learned that there exist packages with prefixes like
- groovyjarjarantlr
- groovyjarjarasm
- groovyjarjarcommonscli
inside the Groovy runtime JAR. Thus removal was not warranted.
The patterns have been deliberately added and constitute a
server class. This commit restores the previous pattern list
for Jetty 11, and makes it largely identical to the list of
Apache Tomcat 10 (compare with TomcatServerConfigurer#createContext).
> Restore missing server class name patterns in Jetty 11

- libs/gretty/src/main/groovy/org/akhikhl/gretty/DefaultLauncher.groovy
Gradle 7.1 will deprecate `JavaExec.getMain()` and `JavaExec.setMain()` in favor of `mainClass` property: https://github.com/gradle/gradle/pull/16734
> Replace deprecated JavaExec.main usage with JavaExec.mainClass property

- jitpack.yml
Addin a `jitpack.yml` allows us to put in any Gradle wrapper version we want. By the way, I found out the instructions from https://github.com/gretty-gradle-plugin/gretty/pull/213#issuecomment-814018918 were wrong (I updated the comment). The change was:
```diff
- dependency.useTarget "com.github.gretty-gradle-plugin.gretty:${dependency.requested.module}:${dependency.requested.version}'"
+ dependency.useTarget "com.github.gretty-gradle-plugin.gretty:${dependency.requested.module}:ff18c0057aeadd4574c32075c95905d2c8ef9ce4'"
```
To work properly, we must coerce all versions to use the specified commit, and not the original version: for the runner projects, the original version might stem from Gretty's build process, which is not what we want.
With this patch and the updated instructions I …
> Build with Gradle 6.x in Jitpack

- .github/workflows/transition.yml
- libs/gretty-common/build.gradle
- libs/gretty-core/build.gradle
- libs/gretty-filter/build.gradle
- libs/gretty-runner-jetty/build.gradle
- libs/gretty-runner-jetty7/build.gradle
- libs/gretty-runner-jetty8/build.gradle
- libs/gretty-runner-jetty9/build.gradle
- libs/gretty-runner-jetty93/build.gradle
- libs/gretty-runner-jetty94/build.gradle
- libs/gretty-runner-tomcat/build.gradle
- libs/gretty-runner-tomcat85/build.gradle
- libs/gretty-runner-tomcat8plus/build.gradle
- libs/gretty-runner-tomcat9/build.gradle
- libs/gretty-runner/build.gradle
- libs/gretty-spock/build.gradle
- libs/gretty-springboot/build.gradle
- libs/gretty-starter/build.gradle
- libs/gretty/src/main/groovy/org/akhikhl/gretty/DefaultLauncher.groovy
- libs/gretty/src/main/groovy/org/akhikhl/gretty/ServletContainerConfig.groovy
Instead of relying on the Groovy versions that Gretty was built with, we must choose Groovy versions at runtime. As a result, the classpath of runner contains Groovy 2 on Gradle 6, and Groovy 3 on Gradle 7.
I commented exhaustively because we might get rid of this behavior when we deprecate support for Gradle 6 / Groovy 2. Actually, just letting the Gretty modules put the Groovy versions on the classpath is much easier to reason about.
Also, the dependencies in the `compileOnly` config are not transitive, such that I had to add Groovy dependencies to all projects, otherwise they would not compile.
The case of `gretty-filter` is particularly interesting (and broken in some instances, to my belief). When adding `gretty-filter`, we mess with the classpath of the webapp. If someone was …
> Pick Groovy versions at runtime / Support JDK 16 (fixes #231)

- .github/workflows/transition.yml
This build has never worked for master.
We set the new minimum JDK requirement to 11, and had this build test the migration rooted in JDK 8.
As a result, we must raise the JDK version for compilation to 11, and the JDK version for test to 17 (the current LTS version).
Let's see if everything works again 🤞
> Rework transition build for master

- .github/workflows/ci.yml
- libs/gretty/build.gradle
@boris-petrov as a follow-up o #236, I took the 'disable validation' route. Let's see if this builds fine 🤞 
Perhaps it's better mid-term to eyeball the output of `validatePlugins`until we drop support for Gradle 6 than to stick with and build against old Gradle releases.
> Upgrade to Gradle 7.3.3 #236

- .github/workflows/ci.yml
- libs/gretty/build.gradle
This PR lands the same patch as for #245, just for Gretty 3.x. Let's make sure all the builds pass.
> Upgrade Getrry 3.x to Gradle 7.3.3 #236

- .github/workflows/ci.yml
- .github/workflows/transition.yml
Draft pull request - we'll need to get our versioning and release schedules sorted first. I just wanted to show that Gretty in principle builds against JDK 17, and also does work with Gradle 7.4
> Gradle 7.4 and JDK 17

- libs/gretty/src/main/groovy/org/akhikhl/gretty/JacocoHelper.groovy
- libs/gretty/src/main/groovy/org/akhikhl/gretty/ProjectUtils.groovy
- libs/gretty/src/main/groovy/org/akhikhl/gretty/StartBaseTask.groovy
There is no clear reason to use these internal APIs, and it's preventing me from making changes to internal APIs in https://github.com/gradle/gradle/pull/20868. Please let me know if there are reasons you needed to reference these, and we can try to figure out a good path forward.
I would also like these changes backported to 3.x if they are accepted, I can make a PR for that if you like.
> Replace internal Gradle API usage with public API

- libs/gretty/src/main/groovy/org/akhikhl/gretty/GrettyPlugin.groovy
Fixes #275
Slf4j issues a warning in case the provider is missing. Furthermore, the checked provider list might not be complete and is currently outdated resulting in false-positives.
> Remove check for missing slf4j provider

- libs/gretty-runner/src/main/groovy/org/akhikhl/gretty/Runner.groovy
Additional change to address restart issues with issue 293
> Use appropriate class loader for servermanger commands

- libs/gretty-runner-jetty11/src/main/groovy/org/akhikhl/gretty/JettyConfigurerImpl.groovy
> fix jettyStart throws exception if using jetty-env.xml

- libs/gretty/src/main/groovy/org/akhikhl/gretty/scanner/BaseScannerManager.groovy
When hotreload is enabled, gretty watches and always recompile/redeploy webapp if there are any changes in "src/java" or "src/resources". That is inconvenient when one has many static resources in "src/resources" that don't require recompilation/redeploy.
This change makes sure that fastReload check is performed before recompile check for sources. So as a workaround one can specify such folders under `src/resources` as fastReload and prevent recompilation/redeploy.
> Support folders under "src/resources" in fastReload configuration property

- libs/gretty-runner/src/main/groovy/org/akhikhl/gretty/Runner.groovy
Redeploy would fail because runner classloader is separate from the servlet container classloader. So runner was not able to create new WebAppContext.
> Fix jetty redeploy with custom jetty-env.xml

- libs/gretty/src/main/groovy/org/akhikhl/gretty/ProjectUtils.groovy
This PR prevents an issue with resolving these artifacts when Gradle switches to Groovy 4 in Gradle 9.0.
> Check for Groovy >= 4 and use correct coordinates
